services:
  - type: web
    name: incubyte-dealership-api
    env: node
    buildCommand: npm install --include=dev && npm run build -w server
    startCommand: npm run db:migrate -w server && npm run start -w server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    plan: free
